#!/usr/bin/env python3
"""Hand-authored data for tag-icon sourcing: the alias table, the axis grouping,
the palette swatches, and the licence facts for each set.

This is the file with the work in it. `ALIASES` is the bridge between two
vocabularies that do not agree — no icon set has "animist solarpunk", but several
have a sprout, a rocket and a recycle mark, which is what the tag is made of.
Everything else in this directory is machinery that can be re-derived.

Adding a tag to the mockup means: give it an axis in AXES, and (usually) a row in
ALIASES. The literal tag name is always tried first, so obvious ones need nothing.
"""
from __future__ import annotations

# --- tag -> icon names to search for, best candidate first --------------------
# Keep these as *icon* words, not tag words: the sets speak UI, not art history.
ALIASES = {
    # creatures
    "bear": ["bear", "teddy-bear", "paw", "polar-bear"],
    "whale": ["whale", "fish", "dolphin"],
    "bird": ["bird", "feather", "dove", "wing"],
    "elephant": ["elephant"],
    "owl": ["owl", "bird"],
    "bee": ["bee", "honey", "honeycomb", "hexagon"],
    "bison": ["cow", "bison", "buffalo", "ox"],
    "rhino": ["rhinoceros", "rhino"],
    "butterfly": ["butterfly"],
    "megafauna": ["mammoth", "elephant", "bones", "dinosaur"],
    "sandhill crane": ["bird", "crane-bird", "flamingo"],
    "crocodilian": ["crocodile", "lizard", "alligator"],
    "turtle": ["turtle", "tortoise"],
    "puma": ["cat", "paw", "lion"],
    "robot": ["robot", "android"],
    "ghost": ["ghost"],
    "octopus": ["octopus", "squid"],
    "narwhal": ["whale", "fish"],
    "giraffe": ["giraffe"],
    "ant": ["ant", "bug", "insect"],
    "dragonfly": ["dragonfly", "bug"],
    "worm": ["worm", "bug"],
    "creature": ["paw", "bug", "alien"],
    "animal portrait": ["paw", "dog", "cat"],
    "insect": ["bug", "spider", "ant"],
    # plants, land, sky
    "tree": ["tree", "tree-deciduous", "pine-tree", "forest"],
    "conifer": ["pine-tree", "tree-evergreen", "christmas-tree", "tree"],
    "juniper": ["tree-deciduous", "tree", "pine-tree"],
    "alligator juniper": ["tree-deciduous", "tree"],
    "ancient tree": ["tree-deciduous", "tree"],
    "cloud": ["cloud", "cloudy"],
    "sky": ["cloud", "sun-cloud", "horizon"],
    "weather": ["cloud-sun", "weather-partly-cloudy", "cloud"],
    "lightning": ["zap", "bolt", "cloud-lightning", "high-voltage"],
    "lightning strike": ["zap", "cloud-lightning", "bolt"],
    "rain": ["cloud-rain", "umbrella", "droplet"],
    "monsoon": ["cloud-rain", "umbrella"],
    "wildfire": ["flame", "fire", "campfire"],
    "drought": ["sun", "thermometer-sun", "droplet-off", "desert"],
    "moon": ["moon", "moon-stars", "crescent-moon"],
    "lunar cycle": ["moon-stars", "moon", "moon-phase"],
    "sun": ["sun", "sunrise"],
    "twilight": ["sunset", "sunrise", "mountain-sun"],
    "night": ["moon", "moon-stars", "stars"],
    "seasons": ["leaf", "sun-snow", "calendar"],
    "autumn": ["leaf", "maple-leaf", "falling-leaf"],
    "solstice": ["sun", "sunrise"],
    "equinox": ["scale", "sun"],
    "rainbow": ["rainbow"],
    "desert": ["cactus", "desert", "sun"],
    "cactus": ["cactus"],
    "mushroom": ["mushroom"],
    "flower": ["flower", "flower-2", "sunflower", "rose"],
    "corn": ["corn", "wheat", "ear-of-corn"],
    "blue corn": ["corn", "ear-of-corn"],
    "seed": ["seedling", "sprout", "seed", "leaf"],
    "garden": ["sprout", "shovel", "watering-can", "seedling"],
    "harvest": ["wheat", "basket", "corn"],
    "food": ["apple", "bread", "utensils"],
    "agriculture": ["tractor", "wheat", "sprout"],
    "landscape": ["mountain", "mountains", "landscape"],
    "mountains": ["mountain", "mountains"],
    "canyon": ["mountain", "layers", "mountains"],
    "geology": ["layers", "mountain", "gem", "rock"],
    "ocean": ["waves", "wave", "water", "anchor"],
    "great plains": ["horizon", "landscape", "grass"],
    "ice": ["snowflake", "ice", "iceberg"],
    "shade": ["umbrella", "cloud", "parasol"],
    # human & body
    "figure": ["user", "person", "person-standing", "walk"],
    "portrait": ["user-square", "user", "frame", "person"],
    "self portrait": ["user-circle", "mirror", "user-square"],
    "face": ["smiley", "user", "face-id", "mood-neutral"],
    "head": ["brain", "user", "head-side"],
    "hand": ["hand", "hand-metal", "handshake"],
    "eyes": ["eye", "eyes"],
    "gaze": ["eye", "eye-scan", "binoculars"],
    "skull": ["skull", "skull-2", "bone"],
    "anatomy": ["bone", "skeleton", "lungs", "heart"],
    "ribcage": ["lungs", "bone", "ribcage"],
    "crowd": ["users", "people", "user-group"],
    "family": ["users", "home-heart", "family"],
    "mask": ["mask", "venetian-mask", "theater-masks"],
    "intimacy": ["heart", "hands-holding", "handshake"],
    "profile": ["user", "face-id"],
    "memento mori": ["skull", "hourglass", "bone"],
    "jeannie": ["heart", "user-heart"],
    "buddha": ["yin-yang", "lotus", "person-meditate"],
    # objects, tools, technology
    "still life": ["bowl", "vase", "cup", "apple"],
    "coffee": ["coffee", "cup", "mug"],
    "vessel": ["vase", "jar", "bottle"],
    "glass jar": ["jar", "bottle", "flask"],
    "domestic object": ["lamp", "chair", "home"],
    "machine": ["cog", "settings", "gear", "engine"],
    "tool": ["hammer", "tool", "wrench"],
    "rocket": ["rocket"],
    "spacecraft": ["rocket", "satellite", "ufo"],
    "space helmet": ["helmet", "astronaut-helmet", "circle-dot"],
    "space exploration": ["rocket", "planet", "telescope"],
    "flying saucer": ["ufo", "flying-saucer"],
    "satellite dish": ["satellite-dish", "antenna", "radar"],
    "antenna": ["antenna", "radio", "wifi"],
    "network": ["network", "share", "git-branch", "hierarchy"],
    "energy": ["zap", "battery", "plug", "bolt"],
    "communication": ["radio", "message", "broadcast", "wifi"],
    "sound": ["volume", "speaker", "waveform", "music"],
    "music": ["music", "music-note"],
    "analog": ["typewriter", "radio", "vinyl", "cassette"],
    "origami": ["paper-crane", "origami", "triangle"],
    "kite": ["kite"],
    "airship": ["zeppelin", "balloon", "hot-air-balloon"],
    "flight": ["plane", "feather", "wind", "paper-plane"],
    "coracle": ["sailboat", "boat", "ship"],
    "tether": ["link", "rope", "anchor"],
    "specimen": ["bug", "pin", "microscope"],
    "breathing apparatus": ["lungs", "mask", "oxygen"],
    "clovis point": ["arrow-up", "triangle", "spear"],
    "teardrop trailer": ["caravan", "camper", "trailer", "car"],
    "crystal": ["diamond", "gem", "crystal-ball"],
    "molecule": ["atom", "molecule", "circles"],
    "mathematics": ["math", "calculator", "sigma", "pi"],
    "fibonacci": ["spiral", "shell", "golden-ratio"],
    "physics": ["atom", "orbit"],
    "sacred geometry": ["hexagon", "triangle", "flower-of-life"],
    # form & composition
    "abstraction": ["shapes", "square-circle", "blob"],
    "line work": ["line", "pen", "scribble", "signature"],
    "geometry": ["triangle-square-circle", "shapes", "ruler", "protractor"],
    "gestural": ["brush", "scribble", "signature"],
    "pattern": ["grid-pattern", "layout-grid", "texture"],
    "triangle": ["triangle"],
    "circle": ["circle"],
    "square": ["square"],
    "sphere": ["sphere", "circle", "globe"],
    "concentric": ["target", "circles", "radar"],
    "spiral": ["spiral", "loader"],
    "grid": ["grid", "layout-grid", "grid-3x3"],
    "scatter": ["scatter-plot", "dots", "chart-dots"],
    "radial": ["sun", "asterisk", "radar"],
    "symmetry": ["flip-horizontal", "symmetry", "mirror"],
    "tessellation": ["hexagon", "grid", "shapes"],
    "minimal": ["minus", "circle", "square"],
    "negative space": ["square-dashed", "crop", "frame"],
    "close crop": ["crop", "zoom-in", "focus"],
    "horizon": ["horizon", "minus", "landscape"],
    "looking up": ["arrow-up", "eye-up", "chevron-up"],
    "perspective": ["perspective", "box", "cube"],
    "faceted": ["diamond", "polygon", "gem"],
    "framed": ["frame", "photo", "picture-in-picture"],
    "small format": ["minimize", "square-small", "zoom-out"],
    "large format": ["maximize", "expand", "zoom-in"],
    "panoramic format": ["panorama", "rectangle-wide", "image"],
    "vertical format": ["rectangle-vertical", "crop-portrait"],
    "narrow format": ["rectangle-vertical", "columns"],
    "square format": ["square", "crop-square"],
    "polyptych": ["columns", "layout-grid", "panels"],
    "enso": ["circle", "circle-dashed", "loader-circle"],
    "thick impasto": ["brush", "palette", "layers"],
    "black and white": ["contrast", "circle-half", "yin-yang"],
    "grisaille": ["contrast", "circle-half"],
    "high chroma": ["palette", "droplet", "color-swatch"],
    "flat ground": ["square", "layers", "rectangle"],
    "crosshatching": ["hash", "grid", "texture"],
    "plate tone": ["texture", "square", "layers"],
    "contour line": ["pen", "line", "vector"],
    "realism": ["eye", "camera", "focus"],
    "stripes": ["menu", "lines", "barcode"],
    "gradient": ["gradient", "contrast", "droplet"],
    # process & practice
    "hand-colored": ["brush", "palette", "paint-bucket", "droplet"],
    "hand-torn paper": ["file", "paper", "scroll", "tear"],
    "found wood": ["log", "wood", "tree-deciduous", "plank"],
    "gold leaf": ["sparkles", "star", "award"],
    "assemblage": ["layers", "puzzle", "blocks", "stack"],
    "site-specific": ["map-pin", "pin", "location"],
    "edition variants": ["copy", "layers", "files"],
    "open edition": ["infinity", "copy", "repeat"],
    "artist proof": ["stamp", "badge", "check"],
    "chine-colle": ["layers", "paper", "files"],
    "direct carving": ["chisel", "hammer", "pickaxe"],
    "work in progress": ["hourglass", "loader", "progress"],
    "plein air": ["easel", "sun", "mountain-sun"],
    "photograph": ["camera", "photo", "aperture"],
    "studio": ["easel", "lamp", "home"],
    "studio journal": ["notebook", "book", "pencil"],
    "mixed media": ["layers", "palette", "shapes"],
    "works on paper": ["file", "paper", "scroll"],
    "reworked painting": ["repeat", "rotate", "refresh"],
    "slow painting": ["hourglass", "clock", "snail"],
    "repetition": ["repeat", "copy", "infinity"],
    "series": ["layers", "copy", "files"],
    "process": ["cog", "workflow", "refresh"],
    "installation view": ["frame", "gallery", "layout"],
    "survey": ["list", "layout-grid", "table"],
    "archive": ["archive", "box", "folder"],
    "exhibition": ["frame", "gallery", "building-museum"],
    # themes
    "humor": ["smile", "laugh", "mood-happy"],
    "absurdism": ["shuffle", "mood-crazy-happy", "sparkles"],
    "deep time": ["hourglass", "history", "clock", "layers"],
    "time": ["clock", "hourglass"],
    "cyclic time": ["refresh", "repeat", "infinity"],
    "memory": ["brain", "history", "bookmark"],
    "aging": ["hourglass", "clock", "tree-deciduous"],
    "salvage": ["recycle", "wrench", "package"],
    "mutual aid": ["handshake", "heart-handshake", "hands-holding"],
    "extinction": ["skull", "bone", "trending-down"],
    "de-extinction": ["refresh", "sprout", "dna"],
    "climate grief": ["thermometer-sun", "heart-crack", "leaf-off"],
    "climate change": ["thermometer-sun", "globe", "trending-up"],
    "grief": ["heart-crack", "cloud-rain"],
    "awe": ["sparkles", "star", "eye"],
    "tenderness": ["heart", "hand-heart"],
    "survival": ["shield", "flame", "heart-pulse"],
    "adaptation": ["shuffle", "refresh", "dna"],
    "transplant": ["sprout", "move", "arrow-right"],
    "migration": ["arrow-right", "bird", "route"],
    "wildness": ["tree", "paw", "mountain"],
    "solitude": ["user", "moon", "tree"],
    "patience": ["hourglass", "clock", "snail"],
    "attention": ["eye", "focus", "target"],
    "balance": ["scale", "balance", "yin-yang"],
    "interdependence": ["link", "network", "handshake"],
    "ecology": ["leaf", "globe", "recycle"],
    "preservation": ["jar", "shield", "archive"],
    "domesticity": ["home", "cup", "lamp"],
    "everyday ritual": ["cup", "sunrise", "repeat"],
    "mundane": ["cup", "box", "circle"],
    "companionship": ["users", "handshake", "heart"],
    "community": ["users", "home", "heart-handshake"],
    "play": ["dice", "puzzle", "kite"],
    "fable": ["book-open", "feather", "sparkles"],
    "myth": ["book-open", "star", "sparkles"],
    "philosophy": ["book-open", "brain", "owl"],
    "wittgenstein": ["book-open", "message-question", "brain"],
    "artificial intelligence": ["cpu", "brain-circuit", "robot"],
    "human and machine": ["handshake", "cpu", "robot"],
    "poem": ["feather", "book-open", "pen"],
    "zen": ["yin-yang", "circle", "lotus"],
    "meditation": ["yin-yang", "lotus", "person-meditate"],
    "buddhism": ["yin-yang", "lotus", "dharma"],
    "first contact": ["ufo", "alien", "radio"],
    "anthropocentrism": ["user", "globe", "crown"],
    "intelligence of nature": ["brain", "leaf", "network"],
    "being seen": ["eye", "eye-scan", "spotlight"],
    "animist solarpunk": ["sprout", "rocket", "recycle", "solar-panel"],
    "post-collapse": ["building-broken", "recycle", "trending-down", "wrench"],
    "the memory of atmosphere": ["cloud", "wind", "cloud-lightning"],
    "geometric anatomy": ["bone", "triangle", "polygon"],
    "cross-medium motif": ["shuffle", "repeat", "arrows-exchange"],
    "recurring motif": ["repeat", "refresh", "infinity"],
    "companion piece": ["copy", "columns", "link"],
    "language game": ["message", "puzzle", "dice"],
    "meaning is use": ["message", "book-open", "puzzle"],
    # place & provenance
    "new mexico": ["map-pin", "map", "cactus"],
    "montana": ["mountain", "map-pin", "tree"],
    "truth or consequences": ["map-pin", "home", "building"],
    "desert archaic": ["building-store", "frame", "home"],
    "rio grande": ["waves", "route", "river"],
    "gila": ["tree", "mountain", "map-pin"],
    "private collection": ["home", "lock", "bookmark"],
    "sold": ["circle-check", "tag", "receipt"],
    "on loan": ["arrow-right-left", "share", "handshake"],
    "pandemic": ["virus", "mask", "shield"],
    "hiking": ["boot", "backpack", "mountain", "footprints"],
    "camping": ["tent", "campfire", "backpack"],
    "biography": ["user", "book-open", "history"],
}

# --- palette tags ------------------------------------------------------------
# Colour tags get a swatch, not an icon — no set has a candidate for "ochre", and
# none should. Hexes are sampled from the works each tag appears on.
PALETTE = {
    "orange": "#c8622a", "blue": "#2f5d84", "green": "#4f6b3a", "white": "#f2eee7",
    "yellow": "#d8a72b", "red": "#a83226", "gray": "#8a8279", "pink": "#d38f9a",
    "teal": "#2f7d7a", "gold": "#b8912f", "ochre": "#b07d2a", "purple": "#6a4b7d",
    "turquoise": "#3aa39b", "black": "#1e1a16", "coral": "#d2705a", "cream": "#efe4d2",
    "navy": "#22374f", "lavender": "#9a8fbd", "mauve": "#9d7681", "rust": "#9c4a2a",
    "violet": "#7b5ea3", "terracotta": "#b45f42", "olive": "#6b6b34", "peach": "#e2a583",
    "plum": "#6d3a52", "magenta": "#a83a72", "amber": "#c98f22", "salmon": "#df8b74",
    "aqua": "#7fc3c0", "tan": "#b99a72", "periwinkle": "#8fa2d4", "beige": "#d9cbb4",
    "rose": "#c08592", "brown": "#6b4a32",
}

# --- axis grouping for the mockup --------------------------------------------
# Only tags listed here appear in the sheet. This is the "icon-worthy" judgement:
# concrete subjects and practices in, pure abstractions out.
AXIS = {}
for name, tags in [
    ("Creatures", ["creature", "bird", "whale", "bear", "elephant", "owl", "bee", "bison",
                   "rhino", "butterfly", "megafauna", "sandhill crane", "crocodilian",
                   "turtle", "puma", "robot", "ghost", "narwhal", "octopus", "giraffe",
                   "ant", "dragonfly", "worm", "insect", "animal portrait"]),
    ("Plants, land & sky", ["tree", "cloud", "sky", "desert", "juniper", "alligator juniper",
                            "conifer", "landscape", "lightning", "geology", "moon",
                            "mountains", "garden", "seed", "corn", "cactus", "canyon",
                            "flower", "mushroom", "sun", "lunar cycle", "rain", "wildfire",
                            "drought", "harvest", "food", "agriculture", "weather",
                            "rainbow", "twilight", "autumn", "seasons", "solstice",
                            "ocean", "night", "ice", "shade", "horizon"]),
    ("Human & body", ["figure", "portrait", "face", "anatomy", "head", "hand", "skull",
                      "crowd", "profile", "mask", "eyes", "gaze", "ribcage", "family",
                      "self portrait", "intimacy", "memento mori", "buddha"]),
    ("Objects & technology", ["still life", "machine", "space helmet", "glass jar", "tool",
                              "tether", "breathing apparatus", "satellite dish", "spacecraft",
                              "technology", "coffee", "domestic object", "origami", "airship",
                              "antenna", "network", "rocket", "coracle", "flight", "vessel",
                              "specimen", "analog", "energy", "communication", "sound",
                              "clovis point", "flying saucer", "teardrop trailer", "kite",
                              "crystal", "molecule", "mathematics", "fibonacci",
                              "space exploration", "music"]),
    ("Themes", ["humor", "deep time", "salvage", "time", "memory", "absurdism", "awe",
                "mutual aid", "extinction", "tenderness", "climate grief", "grief",
                "balance", "survival", "attention", "patience", "solitude", "wildness",
                "everyday ritual", "mundane", "interdependence", "adaptation",
                "climate change", "transplant", "de-extinction", "intelligence of nature",
                "anthropocentrism", "ecology", "fable", "myth", "cyclic time",
                "preservation", "first contact", "migration", "domesticity",
                "companionship", "community", "joy", "play", "poem", "zen", "meditation",
                "philosophy", "wittgenstein", "artificial intelligence",
                "human and machine", "being seen", "aging"]),
    ("Series & bodies of work", ["animist solarpunk", "post-collapse",
                                 "the memory of atmosphere", "geometric anatomy",
                                 "cross-medium motif", "recurring motif", "companion piece",
                                 "series", "language game", "meaning is use", "exhibition",
                                 "installation view", "survey", "archive"]),
    ("Form & surface", ["abstraction", "line work", "geometry", "gestural", "pattern",
                        "triangle", "circle", "square", "sphere", "concentric", "spiral",
                        "grid", "scatter", "radial", "symmetry", "tessellation", "minimal",
                        "negative space", "close crop", "looking up", "perspective",
                        "faceted", "framed", "small format", "large format",
                        "panoramic format", "vertical format", "polyptych", "enso",
                        "thick impasto", "black and white", "crosshatching", "plate tone",
                        "contour line", "realism", "stripes"]),
    ("Practice & provenance", ["hand-colored", "hand-torn paper", "found wood", "gold leaf",
                               "assemblage", "site-specific", "edition variants",
                               "open edition", "artist proof", "chine-colle",
                               "direct carving", "work in progress", "plein air",
                               "photograph", "studio", "studio journal", "mixed media",
                               "works on paper", "reworked painting", "slow painting",
                               "repetition", "process", "private collection", "sold",
                               "on loan", "pandemic", "biography"]),
    ("Place", ["new mexico", "montana", "truth or consequences", "desert archaic",
               "rio grande", "gila", "hiking", "camping"]),
]:
    for t in tags:
        AXIS[t] = name
AXIS_ORDER = ["Creatures", "Plants, land & sky", "Human & body", "Objects & technology",
              "Themes", "Series & bodies of work", "Form & surface",
              "Practice & provenance", "Place"]

AXIS_ORDER = ["Creatures", "Plants, land & sky", "Human & body", "Objects & technology",
              "Themes", "Series & bodies of work", "Form & surface",
              "Practice & provenance", "Place"]

# --- the sets ----------------------------------------------------------------
# npm package -> (display name, licence, obligation). Licences were read from each
# package's own package.json, not from memory; re-check on upgrade.
SETS = {
    "lucide-static":        ("Lucide",          "ISC",          "credit"),
    "@tabler/icons":        ("Tabler",          "MIT",          "credit"),
    "@phosphor-icons/core": ("Phosphor",        "MIT",          "credit"),
    "feather-icons":        ("Feather",         "MIT",          "credit"),
    "heroicons":            ("Heroicons",       "MIT",          "credit"),
    "iconoir":              ("Iconoir",         "MIT",          "credit"),
    "remixicon":            ("Remix",           "Apache-2.0",   "credit + NOTICE"),
    "bootstrap-icons":      ("Bootstrap",       "MIT",          "credit"),
    "@mdi/svg":             ("Material Design", "Apache-2.0",   "credit + NOTICE"),
    "openmoji":             ("OpenMoji",        "CC-BY-SA-4.0", "credit + share-alike"),
}

# Display label per indexed style key (one package can yield more than one style).
SET_LABEL = {
    "lucide": "Lucide", "tabler": "Tabler", "phosphor": "Phosphor",
    "phosphor-thin": "Phosphor thin", "feather": "Feather", "heroicons": "Heroicons",
    "iconoir": "Iconoir", "bootstrap": "Bootstrap", "remix": "Remix", "mdi": "Material",
    "openmoji-black": "OpenMoji line", "openmoji-color": "OpenMoji colour",
}
